module "os"
function version() end
function getComputerID() end
function getComputerLabel() end
function setComputerLabel() end
function run() end
function loadAPI() end
function unloadAPI() end
function pullEvent() end
function pullEventRaw() end
function queueEvent() end
function clock() end
function startTimer() end
function sleep() end
function time() end
function day() end
function setAlarm() end
function shutdown() end
function reboot() end